version: '3.7'

services:

  postgres:
    restart: "unless-stopped"
    image: "postgres"
    ports: 
      - '5432:5432'
    networks:
      - app_net
    env_file:
      - .env

  redis:
    restart: "unless-stopped"
    image: "redis"
    ports:
      - '6379:6379'
    networks:
      - app_net
    env_file:
      - .env

networks:
  app_net:
    driver: "bridge"