version: '3.7'

services:

  tests:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: ./build/tests/Dockerfile
    depends_on:
      - redis_test
      - postgres_test
      - faketarget
      - api
      - rqworker
      - parser
    networks:
      - app_net
    env_file:
      - ./tests/.env.test   

  faketarget:
    image: "halverneus/static-file-server:latest"
    volumes:
      - ./tests/html:/web
    networks:
      - app_net
    environment:
      - PORT=8099
    ports: 
      - '8099:8099'
    
  postgres_test:
    restart: "unless-stopped"
    image: "postgres"
    ports: 
      - '5432:5432'
    networks:
      - app_net
    env_file:
      - ./tests/.env.test
    logging:
      driver: none


  redis_test:
    restart: "unless-stopped"
    image: "redis"
    networks:
      - app_net
    env_file:
      - ./tests/.env.test
    logging:
      driver: none

  api:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: ./build/api/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis_test
      - postgres_test
    networks:
      - app_net
    env_file:
      - ./tests/.env.test
    logging:
      driver: none

  rqworker:
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: ./build/rqworker/Dockerfile
    depends_on:
      - redis_test
      - postgres_test
    networks:
      - app_net
    env_file:
      - ./tests/.env.test
    logging:
      driver: none
  
  parser: 
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: ./build/parser/Dockerfile
    depends_on:
      - redis_test
      - postgres_test
    networks:
      - app_net
    env_file:
      - ./tests/.env.test
    logging:
      driver: none

networks:
  app_net:
    driver: "bridge"